name: 'ClickBOM'
description: 'Download SBOM from GitHub repository, convert to CycloneDX format, and upload to S3'
author: 'Your Name'
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: false
  ghapp-token:
    description: 'GitHub App token for API access'
    required: false
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS region'
    required: false
    default: 'us-east-1'
  s3-bucket:
    description: 'S3 bucket name'
    required: true
  s3-key:
    description: 'S3 object key/path'
    required: false
    default: 'sbom/cyclonedx-sbom.json'
  repository:
    description: 'Repository to download SBOM from (format: owner/repo)'
    required: true
  sbom-format:
    description: 'Final SBOM format (spdx or cyclonedx)'
    required: false
    default: 'cyclonedx'
  clickhouse-url:
    description: 'ClickHouse URL for storing SBOM components data'
    required: false
  clickhouse-port:
    description: 'ClickHouse port'
    required: false
    default: '8123'
  clickhouse-database:
    description: 'ClickHouse database name'
    required: false
    default: 'default'
  clickhouse-username:
    description: 'ClickHouse username'
    required: false
    default: 'default'
  clickhouse-password:
    description: 'ClickHouse password'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
    GHAPP_TOKEN: ${{ inputs.ghapp-token }}
    AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
    AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
    S3_BUCKET: ${{ inputs.s3-bucket }}
    S3_KEY: ${{ inputs.s3-key }}
    REPOSITORY: ${{ inputs.repository }}
    SBOM_FORMAT: ${{ inputs.sbom-format }}
    CLICKHOUSE_URL: ${{ inputs.clickhouse-url }}
    CLICKHOUSE_PORT: ${{ inputs.clickhouse-port }}
    CLICKHOUSE_DATABASE: ${{ inputs.clickhouse-database }}
    CLICKHOUSE_USERNAME: ${{ inputs.clickhouse-username }}
    CLICKHOUSE_PASSWORD: ${{ inputs.clickhouse-password }}
branding:
  icon: 'list'
  color: 'yellow'
