on: [push]
name: Test ClickBOM Action

jobs:
  test_clickbom:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    name: Test ClickBOM Action
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::576599896960:role/GitHubOpenIdConnect
          role-session-name: clickbom-test
          aws-region: us-east-1

      - name: Test ClickBOM Action
        uses: ./
        id: test_clickbom
      