# Once this repository is public, move this workflow to security-integrations
on: [push]
name: Test ClickBOM Action

jobs:
  test_clickbom:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    name: Test ClickBOM Action
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        id: aws-creds
        with:
          role-to-assume: arn:aws:iam::576599896960:role/GitHubOpenIdConnect
          role-session-name: clickbom-test
          aws-region: us-east-1

      - name: Test ClickBOM Action
        uses: ./
        id: test_clickbom
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          aws-access-key-id: ${{ steps.aws-creds.outputs.aws-access-key-id }}
          aws-secret-access-key: ${{ steps.aws-creds.outputs.aws-secret-access-key }}
          s3-bucket: clickhouse-sbom
          s3-key: clickbom.json
          repository: ${{ github.repository }}
